name: food_notifier
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barcode_scan: ^3.0.1
  intl: any
  http: ^0.12.0+1
  provider: any
  shared_preferences: any
  cached_network_image: ^2.3.2+1
  scroll_snap_list: ^0.4.1
  decimal: ^0.3.5

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  fonts:
    - family: NanumMyeongjo
      fonts:
        - asset: fonts/NanumMyeongjo-Regular.ttf
        - asset: fonts/NanumMyeongjo-Bold.ttf
          weight: 700
        - asset: fonts/NanumMyeongjo-ExtraBold.ttf
          weight: 800

  uses-material-design: true